name: Update Dump Index

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-file-structure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Generate dump index
        run: |
          python - <<EOF
          import os
          import json
          import fnmatch

          def read_ignore_patterns(ignore_file='.ignore'):
              patterns = []
              if os.path.exists(ignore_file):
                  with open(ignore_file, 'r') as f:
                      for line in f:
                          line = line.strip()
                          if line and not line.startswith('#'):
                              patterns.append(line)
              return patterns

          def is_ignored(path, patterns):
              for pattern in patterns:
                  if fnmatch.fnmatch(path, pattern) or fnmatch.fnmatch(os.path.basename(path), pattern):
                      return True
              return False

          def get_structure(path='.', base_path='', ignore_patterns=None):
              if ignore_patterns is None:
                  ignore_patterns = []
              structure = {}
              for item in os.listdir(path):
                  if item.startswith('.') or item == 'index.js':
                      continue
                  item_path = os.path.join(path, item)
                  rel_path = os.path.join(base_path, item) if base_path else item
                  if is_ignored(rel_path, ignore_patterns):
                      continue
                  if os.path.isdir(item_path):
                      structure[item] = get_structure(item_path, rel_path, ignore_patterns)
                  elif item.endswith('.md'):
                      structure[item] = None
              return structure

          ignore_patterns = read_ignore_patterns('.ignore')
          file_structure = get_structure(ignore_patterns=ignore_patterns)
          with open('index.js', 'w') as f:
              f.write('const INDEX = ') 
              json.dump(file_structure, f)
              f.write(';')
          EOF

      - name: Commit and push if changed
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add index.js
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update index" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      # NEW STEP: Sync Git repo to S3
      - name: Upload bare repo mirror to Wasabi
        run: |
          # Create bare mirror
          git clone --mirror . repo.git

          # Sync to Wasabi bucket (replace with your endpoint + bucket)
          aws s3 sync repo.git s3://${{ secrets.WASABI_BUCKET_RAW }}/data-dump.git \
            --exclude ".git/*" \
            --delete \
            --exact-timestamps \
            --endpoint-url=https://s3.${{ secrets.WASABI_REGION }}.wasabisys.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.WASABI_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.WASABI_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.WASABI_REGION }}
